import type { Sweet } from "./types"

export const mockSweets: Sweet[] = [
  {
    id: "1",
    name: "Gulab Jamun",
    description: "Soft, spongy balls made from milk solids, soaked in aromatic sugar syrup",
    price: 250,
    image: "/gulab-jamun-indian-sweet.jpg",
    category: "Milk-based",
    quantity: 25,
    ingredients: ["Milk powder", "Sugar", "Cardamom", "Rose water"],
    isVegetarian: true,
    isVegan: false,
    weight: "500g",
  },
  {
    id: "2",
    name: "Rasgulla",
    description: "Spongy white balls made from cottage cheese, cooked in light sugar syrup",
    price: 200,
    image: "/rasgulla-bengali-sweet.jpg",
    category: "Milk-based",
    quantity: 30,
    ingredients: ["Cottage cheese", "Sugar", "Cardamom"],
    isVegetarian: true,
    isVegan: false,
    weight: "500g",
  },
  {
    id: "3",
    name: "Kaju Katli",
    description: "Diamond-shaped cashew fudge, a premium sweet for special occasions",
    price: 800,
    image: "/kaju-katli-cashew-sweet.jpg",
    category: "Dry Fruits",
    quantity: 15,
    ingredients: ["Cashews", "Sugar", "Silver leaf"],
    isVegetarian: true,
    isVegan: true,
    weight: "500g",
  },
  {
    id: "4",
    name: "Jalebi",
    description: "Crispy, spiral-shaped sweet soaked in saffron-flavored sugar syrup",
    price: 180,
    image: "/jalebi-orange-spiral-sweet.jpg",
    category: "Fried",
    quantity: 0,
    ingredients: ["Flour", "Sugar", "Saffron", "Cardamom"],
    isVegetarian: true,
    isVegan: true,
    weight: "500g",
  },
  {
    id: "5",
    name: "Barfi",
    description: "Rich milk-based sweet with pistachios and almonds",
    price: 350,
    image: "/barfi-indian-milk-sweet.jpg",
    category: "Milk-based",
    quantity: 20,
    ingredients: ["Milk", "Sugar", "Pistachios", "Almonds"],
    isVegetarian: true,
    isVegan: false,
    weight: "500g",
  },
  {
    id: "6",
    name: "Laddu",
    description: "Round sweet balls made from gram flour and ghee",
    price: 220,
    image: "/laddu-round-indian-sweet.jpg",
    category: "Traditional",
    quantity: 40,
    ingredients: ["Gram flour", "Ghee", "Sugar", "Cardamom"],
    isVegetarian: true,
    isVegan: false,
    weight: "500g",
  },
]

export const categories = ["All", "Milk-based", "Dry Fruits", "Fried", "Traditional"]
